### ISSUE TITLE
Exception when iOS app running on M1 Mac

### ISSUE THREAD

**Issue by SlonGL** [sadeghgoo/MagicTimer#10] opened 2021-04-15 12:53 UTC
2021-04-15 17:51:36.250058+0500 KickSharing[41952:669837] MagicTimer: initialized
2021-04-15 17:51:36.253818+0500 KickSharing[41952:669837] *** Assertion failure in -[MagicTimer.MGStandardTimerFormatter setAllowedUnits:], NSDateComponentsFormatter.m:806
2021-04-15 17:51:36.260599+0500 KickSharing[41952:669837] [General] Invalid parameter not satisfying: allowedUnits == 0 || !(allowedUnits & ~(NSCalendarUnitYear | NSCalendarUnitMonth | NSCalendarUnitWeekOfMonth | NSCalendarUnitDay | NSCalendarUnitHour | NSCalendarUnitMinute | NSCalendarUnitSecond))

**Comment by abspr** [comment] 2022-02-21 12:11
I faced this crash too.
The problem is in `MGStandardTimerFormatter` class and `converToValidFormat(ti:)` func

the .nanoSecond is not acceptable for converting to string
So it should be this:
`func converToValidFormat(ti: TimeInterval) -> String? {
        switch ti {
        case let x where Int(x) >= MGTimeUnit.hour.rawValue:
            allowedUnits = [.hour, .minute, .second]
        case let x where Int(x) <= MGTimeUnit.hour.rawValue:
            allowedUnits = [.minute, .second]
        default:
            break
        }
        return super.string(from: ti)
    }`

**Comment by sadeghgoo** [comment] 2022-02-22 05:55
Fixed in 1.0.3 version.

**Closed by sadeghgoo** 2022-02-22 05:55 UTC
